platform :ios, '9.0'
use_frameworks!

link_with 'Issues'
link_with 'IssueKit'

# OAuth
pod 'OAuthSwift', :git => 'https://github.com/mwermuth/OAuthSwift.git', :branch => 'swift2.0'

# Networking
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'

# Font Awesome
pod 'Font-Awesome-Swift'

# Images
pod 'HanekeSwift', :git => 'https://github.com/meteochu/HanekeSwift.git', :branch => 'swift-2.0'