platform :ios, '9.0'
use_frameworks!

link_with 'Issues'
link_with 'IssueKit'

# OAuth
pod 'NXOAuth2Client'

# Networking
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift-2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git', :branch => 'xcode7'