platform :ios, '9.0'
use_frameworks!

link_with 'Issues'
link_with 'IssueKit'

# OAuth
pod 'OAuthSwift', '~> 0.5.0'

# Networking
pod 'Alamofire', '~> 3.1.0'
pod 'SwiftyJSON', '~> 2.3.1'

# Font Awesome
pod 'Font-Awesome-Swift'

# Images
pod 'HanekeSwift', '~> 0.10.0'

# Empty tableviews
pod 'DZNEmptyDataSet'